### Scipy - Practice

In [48]:
# imports
import numpy as np
import pandas as pd
from scipy import linalg # Linear Algebra

In [59]:
df = np.genfromtxt('Industrial oils.csv', delimiter=",",skip_header = 1,dtype = 'str')   ## reading a file using numpy
print(df)
print(df.shape)
type (df)   ## note the data type of the object used to read a file using numpy...
df.dtype

[['1' '210' 'Turbine oils' '29']
 ['2' '7' 'Transformer oils' '74']
 ['3' '220' 'Industrial Gear oils' '134']
 ...
 ['2998' '136' 'Hydraulic oils' '27']
 ['2999' '173' 'Transformer oils' '85']
 ['3000' '141' 'Transformer oils' '276']]
(3000, 4)


dtype('<U20')

In [55]:
pddf = pd.read_csv('Industrial oils.csv', delimiter=",")  ## reading a file using pandas
print(pddf)
type(pddf)   ## note the datatype of the object used to read file using pandas...

      Transaction  CustID                  Type  Spent
0               1     210          Turbine oils     29
1               2       7      Transformer oils     74
2               3     220  Industrial Gear oils    134
3               4      93        Compresor Oils    150
4               5      66        Compresor Oils    168
...           ...     ...                   ...    ...
2995         2996     204        Compresor Oils    360
2996         2997      53        Compresor Oils     67
2997         2998     136        Hydraulic oils     27
2998         2999     173      Transformer oils     85
2999         3000     141      Transformer oils    276

[3000 rows x 4 columns]


pandas.core.frame.DataFrame

In [56]:
pddf.dtypes

Transaction     int64
CustID          int64
Type           object
Spent           int64
dtype: object

#### Oil Types
    1 Turbine oils
    2 Transformer oils
    3 Industrial Gear oils
    4 Compresor Oils
    5 Hydraulic oils

In [5]:
# Mapping the Oil Types to nueric values
oilType_map = {
    'Turbine oils':1,
    'Transformer oils':2,
    'Industrial Gear oils':3,
    'Compresor Oils':4,
    'Hydraulic oils': 5
}
# Applying the mapping
oilTypes = []
for i in range(df.shape[0]):
    oilTypes.append([oilType_map[df[i][2]]]) # creating a 2D arrary to make it compatible to merge with df
print(oilTypes)

[[1], [2], [3], [4], [4], [3], [2], [5], [2], [5], [5], [5], [5], [1], [2], [4], [2], [4], [5], [1], [5], [1], [2], [2], [2], [4], [5], [3], [4], [3], [4], [3], [5], [2], [5], [5], [1], [1], [5], [1], [2], [1], [4], [1], [5], [3], [5], [3], [5], [5], [1], [5], [4], [5], [2], [3], [3], [3], [3], [2], [3], [2], [1], [3], [3], [5], [3], [3], [1], [3], [5], [3], [3], [1], [5], [2], [3], [2], [1], [1], [4], [1], [5], [4], [1], [5], [3], [5], [5], [3], [4], [4], [5], [3], [3], [4], [3], [2], [3], [5], [2], [3], [5], [5], [2], [3], [4], [4], [5], [3], [1], [3], [4], [5], [3], [1], [1], [4], [3], [3], [4], [2], [1], [1], [3], [3], [5], [2], [3], [2], [2], [3], [5], [2], [1], [5], [3], [5], [4], [3], [4], [5], [4], [5], [4], [5], [5], [4], [1], [2], [1], [3], [4], [5], [2], [3], [3], [3], [5], [3], [3], [2], [4], [3], [4], [5], [4], [3], [1], [4], [5], [5], [2], [1], [5], [3], [1], [2], [4], [2], [1], [2], [2], [3], [2], [3], [3], [3], [2], [3], [2], [5], [5], [3], [3], [1], [3], [2], [2], [4],

In [61]:
a = df.shape
type(a)
a[0]
a[1]

tuple

In [62]:
# Add the Oil Types as new column to the df array
df = np.append(df,oilTypes, axis=1) # axis=1 for columns
df

array([['1', '210', 'Turbine oils', '29', '1'],
       ['2', '7', 'Transformer oils', '74', '2'],
       ['3', '220', 'Industrial Gear oils', '134', '3'],
       ...,
       ['2998', '136', 'Hydraulic oils', '27', '5'],
       ['2999', '173', 'Transformer oils', '85', '2'],
       ['3000', '141', 'Transformer oils', '276', '2']], dtype='<U20')

In [16]:
# Drop to column having text values
df2 = np.delete(df, 2, axis=1)
print(df2)

[['1' '210' '29' '1']
 ['2' '7' '74' '2']
 ['3' '220' '134' '3']
 ...
 ['2998' '136' '27' '5']
 ['2999' '173' '85' '2']
 ['3000' '141' '276' '2']]


In [17]:
# Convert data type to integer
print('Type of df2-',df2.dtype)
df3 = df2.astype(dtype='int')
print('Type of df3-',df3.dtype)
print(df3)

Type of df2- <U20
Type of df3- int32
[[   1  210   29    1]
 [   2    7   74    2]
 [   3  220  134    3]
 ...
 [2998  136   27    5]
 [2999  173   85    2]
 [3000  141  276    2]]


In [63]:
compressorOilsIndex = []
df_compressorOils = [] #copy Compressor Oils data into new array
for i in range(df3.shape[0]):
    if df3[i][3] == 4:
        np.delete(df3, i, axis=0)
        
df3

array([[   1,  210,   29,    1],
       [   2,    7,   74,    2],
       [   3,  220,  134,    3],
       ...,
       [2998,  136,   27,    5],
       [2999,  173,   85,    2],
       [3000,  141,  276,    2]])

In [18]:
# Remove all rows for 4- Compresor Oils
# Step-1: find all row indexs to remove
compressorOilsIndex = []
df_compressorOils = [] #copy Compressor Oils data into new array
for i in range(df3.shape[0]):
    if df3[i][3] == 4:
        compressorOilsIndex.append(i)
        ##df_compressorOils.append(df3[i][:])

##df_compressorOils = np.array(df_compressorOils)
df3_filtered = np.delete(df3, compressorOilsIndex, axis=0) # axis=0 for rows
print(df3_filtered)
print('df3 shape',df3_filtered.shape)
print(df_compressorOils)
print('df_compressorOils shape',df_compressorOils.shape)

[[   1  210   29    1]
 [   2    7   74    2]
 [   3  220  134    3]
 ...
 [2998  136   27    5]
 [2999  173   85    2]
 [3000  141  276    2]]
df3 shape (2513, 4)
[[   4   93  150    4]
 [   5   66  168    4]
 [  16  174  238    4]
 ...
 [2991  140  138    4]
 [2996  204  360    4]
 [2997   53   67    4]]
df_compressorOils shape (487, 4)


In [19]:
df3.dtype

dtype('int32')

In [24]:
df3.mean()

436.6603333333333

In [20]:
# create a new array
arr = np.array([
    [1, 34, 78],
    [2, 35, 79],
    [4, 37, 81]
])
arr

array([[ 1, 34, 78],
       [ 2, 35, 79],
       [ 4, 37, 81]])

In [21]:
#insert row at end
arr = np.append(arr, [[5, 38, 82]], axis=0) #both array should be same dinesion, i.e. 2D
arr

array([[ 1, 34, 78],
       [ 2, 35, 79],
       [ 4, 37, 81],
       [ 5, 38, 82]])

In [22]:
#insert at specific position
arr = np.insert(arr, 2, [3, 36, 80], axis=0)
arr

array([[ 1, 34, 78],
       [ 2, 35, 79],
       [ 3, 36, 80],
       [ 4, 37, 81],
       [ 5, 38, 82]])

In [23]:
#Subtract 5 from all values in column 3
for i in range(arr.shape[0]):
    arr[i][2] -= 5
arr

array([[ 1, 34, 73],
       [ 2, 35, 74],
       [ 3, 36, 75],
       [ 4, 37, 76],
       [ 5, 38, 77]])

In [29]:
arr.shape[1]

3

In [30]:
ar2 = np.array([[1,2],[2,3],[3,4],[4,5]])

In [31]:
ar2

array([[1, 2],
       [2, 3],
       [3, 4],
       [4, 5]])

In [39]:
s = ar2.shape  ## Result of <variable>.type is a tupple...
s
type(s)

tuple

In [43]:
ar3 = np.array([1,2,3,4,5])
ar3
ar3.shape

(5,)