## basics of python

In [1]:
a = 57
b = 43
c = a-b
c

14

In [2]:
print(c)

14


In [4]:
c=a+b
print(c)
print(type(c))

100
<class 'int'>


In [17]:
x = ('apple','banana')
print(type(x))
print(x[1])
###retrive using index
x[1]='orange'
###tuple is immutable
print(x[1])

<class 'tuple'>
banana


TypeError: 'tuple' object does not support item assignment

In [10]:
y = ['apple', 'banana']
print(type(y))
print(y[1])
###retrive using index
y[1]='orange'
###list is mutable
print(y[1])

<class 'list'>
banana
orange


In [15]:
z = {1,2.3,1,'asd'}
print(type(z))
print(z)
###set removes duplicates
###can't retrive using index
z.remove(2.3)
print(z)
z.add('rej')
print(z)

<class 'set'>
{1, 2.3, 'asd'}
{1, 'asd'}
{1, 'rej', 'asd'}


In [23]:
p = {'india':'delhi','maharastra':'mumbai',1:3,1:4}
print(p)
###dictionary duplicates the previous values
print(p['india'])
###dictionary can be retrived with keys
p['india']='chennai'
print(p['india'])
###dict values are mutable
###dict keys are immutable

{'india': 'delhi', 'maharastra': 'mumbai', 1: 4}
delhi
chennai


In [25]:
a="how are you"
a

'how are you'

In [26]:
a[1]

'o'

In [29]:
a[1]='s'
###string is immutable

TypeError: 'str' object does not support item assignment

In [30]:
import numpy as np

In [32]:
list1=[1,2,3]
np.array(list1)  #convert list to array

array([1, 2, 3])

In [33]:
arr=np.array([2,3,4])
arr

array([2, 3, 4])

In [39]:
list_of_lists=[[1,2,3],[2,3,4],[3,4,5]]
np.array(list_of_lists) #creates matrix

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [37]:
np.arange(2,25)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24])

In [41]:
np.arange(2,24,5) #2 to 24 with interval 5

array([ 2,  7, 12, 17, 22])

In [42]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [44]:
np.zeros(6,dtype=int) #array with all 0's of type int

array([0, 0, 0, 0, 0, 0])

In [45]:
np.ones(4)

array([ 1.,  1.,  1.,  1.])

In [46]:
np.ones(4, dtype=int)

array([1, 1, 1, 1])

In [47]:
np.ones((2,4), dtype=int) #2x4 matrix with all ones

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [50]:
np.linspace(0,20,9)

array([  0. ,   2.5,   5. ,   7.5,  10. ,  12.5,  15. ,  17.5,  20. ])

In [52]:
np.eye(4) #identuty matrix

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [55]:
np.random.rand(2,5) #random 2x4 matrix

array([[ 0.57815459,  0.48833628,  0.43391079,  0.35227454,  0.49774504],
       [ 0.88843746,  0.05231879,  0.88511741,  0.55150447,  0.14214102]])

In [56]:
np.random.randn(2,5)

array([[-0.83324088, -0.14521434, -1.81422548, -0.45018124, -0.74155765],
       [-0.18052253, -2.3579664 ,  0.09491267,  0.52346159, -1.85781102]])

In [58]:
np.random.randint(2,5,4) #random 4 int from 2,3,4 

array([3, 4, 3, 3])

In [59]:
np.random.randint(20,56,100)

array([51, 51, 51, 42, 27, 53, 20, 55, 37, 47, 36, 50, 51, 30, 37, 47, 35,
       55, 28, 55, 25, 40, 24, 36, 29, 55, 50, 26, 47, 35, 45, 34, 35, 41,
       20, 51, 51, 40, 42, 46, 41, 54, 25, 23, 55, 24, 24, 35, 27, 40, 33,
       52, 54, 40, 42, 40, 50, 45, 53, 23, 42, 52, 30, 52, 28, 21, 33, 26,
       54, 33, 43, 30, 52, 48, 50, 39, 55, 54, 32, 50, 50, 46, 47, 34, 20,
       36, 36, 48, 40, 33, 30, 46, 35, 47, 47, 22, 40, 39, 44, 20])

In [61]:
s_arr = np.arange(3,15)
s_arr

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [62]:
s_arr.min()

3

In [65]:
s_arr.argmin() #arg position of min value

0

In [63]:
s_arr.max()

14

In [67]:
s_arr.argmax() #arg position of max value

11

In [70]:
s_arr.dtype

dtype('int32')

In [72]:
s_arr = np.arange(10,25)
s_arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [75]:
s_arr = s_arr.reshape(3,5)
s_arr

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [78]:
s_arr[1]=100 
s_arr

array([[ 10,  11,  12,  13,  14],
       [100, 100, 100, 100, 100],
       [ 20,  21,  22,  23,  24]])

In [80]:
s_arr = np.arange(10,90)
s_arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89])

In [81]:
s_arr[4:8]

array([14, 15, 16, 17])

In [83]:
s_s_arr = s_arr[0:8]
s_s_arr

array([10, 11, 12, 13, 14, 15, 16, 17])

In [84]:
s_arr[:]=1009
s_arr

array([1009, 1009, 1009, 1009, 1009, 1009, 1009, 1009, 1009, 1009, 1009,
       1009, 1009, 1009, 1009, 1009, 1009, 1009, 1009, 1009, 1009, 1009,
       1009, 1009, 1009, 1009, 1009, 1009, 1009, 1009, 1009, 1009, 1009,
       1009, 1009, 1009, 1009, 1009, 1009, 1009, 1009, 1009, 1009, 1009,
       1009, 1009, 1009, 1009, 1009, 1009, 1009, 1009, 1009, 1009, 1009,
       1009, 1009, 1009, 1009, 1009, 1009, 1009, 1009, 1009, 1009, 1009,
       1009, 1009, 1009, 1009, 1009, 1009, 1009, 1009, 1009, 1009, 1009,
       1009, 1009, 1009])

In [86]:
s_mat = np.array(([1,2,3],[3,4,5]))
s_mat

array([[1, 2, 3],
       [3, 4, 5]])

In [87]:
s_mat[1][2]

5

In [88]:
s_mat[:,2]

array([3, 5])

In [89]:
s_mat[1,1]

4

In [90]:
s_mat[0:2,1:2]

array([[2],
       [4]])

In [94]:
s_mat[0:,1:]

array([[2, 3],
       [4, 5]])

In [96]:
s_mat[1]

array([3, 4, 5])

In [98]:
s_arr=np.arange(1,30)
s_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [99]:
s_arr+s_arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58])

In [100]:
np.exp(s_arr)

array([  2.71828183e+00,   7.38905610e+00,   2.00855369e+01,
         5.45981500e+01,   1.48413159e+02,   4.03428793e+02,
         1.09663316e+03,   2.98095799e+03,   8.10308393e+03,
         2.20264658e+04,   5.98741417e+04,   1.62754791e+05,
         4.42413392e+05,   1.20260428e+06,   3.26901737e+06,
         8.88611052e+06,   2.41549528e+07,   6.56599691e+07,
         1.78482301e+08,   4.85165195e+08,   1.31881573e+09,
         3.58491285e+09,   9.74480345e+09,   2.64891221e+10,
         7.20048993e+10,   1.95729609e+11,   5.32048241e+11,
         1.44625706e+12,   3.93133430e+12])

In [101]:
np.log(s_arr)

array([ 0.        ,  0.69314718,  1.09861229,  1.38629436,  1.60943791,
        1.79175947,  1.94591015,  2.07944154,  2.19722458,  2.30258509,
        2.39789527,  2.48490665,  2.56494936,  2.63905733,  2.7080502 ,
        2.77258872,  2.83321334,  2.89037176,  2.94443898,  2.99573227,
        3.04452244,  3.09104245,  3.13549422,  3.17805383,  3.21887582,
        3.25809654,  3.29583687,  3.33220451,  3.36729583])

In [102]:
np.max(s_arr)

29

In [103]:
np.min(s_arr)

1

In [104]:
np.argmin(s_arr)

0

In [105]:
np.argmax(s_arr)

28

In [106]:
np.square(s_arr)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676,
       729, 784, 841], dtype=int32)

In [107]:
np.std(s_arr)

8.3666002653407556

In [108]:
np.var(s_arr)

70.0

In [109]:
np.mean(s_arr)

15.0

In [113]:
arr=np.random.randn(3,5)
arr

array([[ 0.65243389, -1.8879124 , -1.0556531 ,  0.82363074,  1.06478968],
       [ 0.6702996 ,  0.4035232 , -1.12430018,  0.33408854, -1.44503059],
       [-1.1651571 , -0.18678353,  1.27370612, -0.18307532, -0.33574127]])

In [114]:
np.round(arr,decimals=3)

array([[ 0.652, -1.888, -1.056,  0.824,  1.065],
       [ 0.67 ,  0.404, -1.124,  0.334, -1.445],
       [-1.165, -0.187,  1.274, -0.183, -0.336]])

In [115]:
sports=np.array(['golf','cricket','fball','cricket'])
np.unique(sports)

array(['cricket', 'fball', 'golf'], 
      dtype='<U7')